export const copy = {
  ja: {
    title: "別のPCのUSB機器を、",
    accent: "手元のPCで使う。",
    description: "RemoteUSBは、ネットワーク経由でUSB機器を接続・共有できるWindows用アプリです。無料で利用でき、ソースコードも公開しています。",
    download: "SourceForgeからダウンロード",
    start: "使い方を見る",
    free: "無料・オープンソース",
    guide: "/ja/guide.html",
    screenshot: "ja",
    preview: "接続できるUSB機器を一覧で確認",
    previewDescription: "機器の検索や接続・切断、サーバーの管理をアプリから操作できます。",
    imageAlt: "RemoteUSBのデバイス一覧画面",
    caption: "デモモードの画面です。表示されている機器や接続状態は、実際のものではありません。",
    featuresTitle: "RemoteUSBでできること",
    features: [
      [
        "USB機器の接続・共有",
        "別のPCで共有されているUSB機器に接続できます。手元のPCにつないだUSB機器を、ほかのPCに共有することもできます。",
      ],
      [
        "接続状態の確認と自動再接続",
        "USB機器の接続状態を一覧で確認できます。機器ごとに自動再接続を設定すると、接続が切れた際に再接続を試みます。",
      ],
      [
        "テーマと言語の切り替え",
        "ライト・ダークテーマを選べます。日本語・英語・韓国語・簡体字中国語に対応し、タスクトレイへの常駐も可能です。",
      ],
    ],
    setupTitle: "使い始めるには",
    steps: [
      [
        "アプリをインストール",
        "SourceForgeからWindows用インストーラーをダウンロードし、実行します。",
      ],
      [
        "USB機器を共有し、接続先を登録",
        "USB機器をつないだPCで共有を設定します。利用する側のRemoteUSBには、共有元のホスト名とポートを登録します。信頼できるLANやVPN内で使用してください。",
      ],
      [
        "使いたい機器に接続",
        "デバイス一覧を更新し、使いたい機器の「接続」ボタンを押します。詳しい設定方法はガイドをご覧ください。",
      ],
    ],
    cta: "RemoteUSBをダウンロード",
    ctaDescription: "ボタンをクリックすると、SourceForgeから最新版のダウンロードが始まります。",
    note: "現在は開発初期のバージョンです。対応環境や既知の制限については、ガイドをご確認ください。",
    source: "ソースコードを見る",
  },
  en: {
    title: "Your USB devices.", accent: "Within reach.",
    description: "Bring USB devices from another PC to your Windows desktop. RemoteUSB is a free, open-source app for connecting and sharing USB over your network.",
    download: "Download from SourceForge", start: "Read the guide", free: "Free & open source", guide: "/guide.html", screenshot: "en",
    preview: "Every device. In view.", previewDescription: "Find, connect, and share. Manage your devices in one familiar interface.",
    imageAlt: "RemoteUSB device dashboard", caption: "App shown in demo mode. Devices and connections are simulated.",
    featuresTitle: "Less setup. More connection.",
    features: [["Connect and share.", "Connect to USB devices shared by another PC, or share devices attached to yours. Client and server controls live in one app."], ["See your connections.", "Search devices, manage servers, and check connection status. Enable automatic reconnection for individual devices."], ["Make yourself at home.", "Choose light or dark mode and one of four languages. Keep RemoteUSB in the system tray, ready when you need it."]],
    setupTitle: "Three steps to get connected.",
    steps: [["Download", "Get the Windows installer from SourceForge and run setup."], ["Add a server", "Share a USB device over a trusted LAN or VPN, then add the server hostname and port."], ["Connect a device", "Refresh the list and connect to your device. Find detailed setup instructions in the guide."]],
    cta: "Go beyond the USB cable.", ctaDescription: "Download RemoteUSB and get started with your own setup.", note: "Early-stage software. Check the guide for hardware compatibility and requirements.", source: "Explore the source",
  },
  ko: {
    title: "익숙한 USB를,", accent: "더 자유롭게.",
    description: "다른 PC의 USB 장치를 내 Windows에서. RemoteUSB는 네트워크를 통한 USB 연결과 공유를 한곳에 모은 무료 오픈 소스 앱입니다.",
    download: "SourceForge에서 다운로드", start: "사용 가이드", free: "무료 · 오픈 소스", guide: "/ko/guide.html", screenshot: "ko",
    preview: "모든 장치를 한눈에.", previewDescription: "검색, 연결, 공유. 하나의 화면에서 장치를 관리하세요.", imageAlt: "RemoteUSB 장치 목록 화면", caption: "데모 모드 화면입니다. 장치와 연결은 시뮬레이션입니다.",
    featuresTitle: "더 간편한 USB 연결.",
    features: [["연결과 공유를 함께.", "다른 PC가 공유한 USB에 연결하거나 내 PC의 USB를 공유하세요. 클라이언트와 서버를 하나의 앱에서 관리합니다."], ["연결 상태를 한눈에.", "장치 검색, 서버 관리, 연결 상태 확인을 한곳에서. 장치별 자동 재연결도 지원합니다."], ["내 환경에 맞게.", "라이트·다크 테마와 4개 언어를 지원합니다. 시스템 트레이에서 필요할 때 바로 사용할 수 있습니다."]],
    setupTitle: "세 단계로 시작하세요.", steps: [["다운로드", "SourceForge에서 Windows 설치 프로그램을 받아 설치합니다."], ["서버 추가", "신뢰할 수 있는 LAN 또는 VPN에서 USB를 공유하고 서버의 호스트 이름과 포트를 등록합니다."], ["장치 연결", "목록을 새로 고침하고 장치를 선택해 연결합니다. 자세한 설정은 가이드를 확인하세요."]],
    cta: "USB 케이블 너머로.", ctaDescription: "RemoteUSB를 다운로드하고 내 환경에서 시작하세요.", note: "현재 초기 개발 버전입니다. 하드웨어 호환성과 요구 사항은 가이드를 확인하세요.", source: "소스 코드 보기",
  },
  "zh-CN": {
    title: "熟悉的 USB，", accent: "更自由的连接。",
    description: "在自己的 Windows 上连接另一台电脑的 USB 设备。RemoteUSB 是一款免费的开源应用，让 USB 网络连接与共享集中在一处。",
    download: "从 SourceForge 下载", start: "查看使用指南", free: "免费 · 开源", guide: "/zh-CN/guide.html", screenshot: "zh-CN",
    preview: "所有设备，一目了然。", previewDescription: "查找、连接、共享。在熟悉的界面中管理设备。", imageAlt: "RemoteUSB 设备列表界面", caption: "应用处于演示模式。设备与连接均为模拟。",
    featuresTitle: "让 USB 连接更简单。",
    features: [["连接与共享，一起完成。", "连接其他电脑共享的 USB，或共享本机设备。在一个应用中管理客户端和服务器。"], ["随时掌握连接状态。", "搜索设备、管理服务器、查看连接状态。还可为各个设备启用自动重连。"], ["融入你的工作环境。", "支持浅色、深色主题及四种语言。驻留系统托盘，需要时随时访问。"]],
    setupTitle: "三步开始连接。", steps: [["下载", "从 SourceForge 获取 Windows 安装程序并完成安装。"], ["添加服务器", "在可信的局域网或 VPN 上共享 USB，添加服务器主机名和端口。"], ["连接设备", "刷新列表，选择需要的设备并连接。详细设置请参阅指南。"]],
    cta: "不再局限于 USB 线缆。", ctaDescription: "下载 RemoteUSB，在你的环境中开始使用。", note: "目前为早期开发版本。硬件兼容性与运行要求请参阅指南。", source: "查看源代码",
  },
};
